name: CI - Compile

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run:  |
        sudo apt-get install ruby
        sudo gem install ceedling
        sudo python -m pip install gcovr

    - name: Compile
      run: mkdir -p build && cd build && cmake .. && make -j8