name: CI - Compile

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run:  |
        sudo apt-get update
        sudo apt-get install git build-essential libusb-1.0-0-dev swig cmake python-dev libconfuse-dev libboost-all-dev autoconf automake libtool
        cd vendor/libftdi1 && mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX="/usr/" ../ && make -j8 && make install
        cd vendor/libmpsse/src && autoreconf --install && ./configure && make -j8 && make install

    - name: Compile
      run: mkdir -p build && cd build && cmake .. && make -j8